#!/usr/bin/env python3
"""Convert MySQL DDL (from ruoyi-vue-pro.sql) to H2 compatible SQL."""
import re, sys

def convert_mysql_to_h2(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # 1. Remove backticks
    content = content.replace('`', '')

    # 2. Remove CHARACTER SET + COLLATE clauses
    content = re.sub(r'\s+CHARACTER SET \w+', '', content)
    content = re.sub(r'\s+COLLATE \w+', '', content)

    # 3. Remove USING BTREE
    content = re.sub(r'\s+USING BTREE', '', content)

    # 4. Remove ENGINE=InnoDB ... and other table options
    content = re.sub(r'ENGINE\s*=\s*\w+.*?(?=;|\n)', '', content)
    content = re.sub(r'AUTO_INCREMENT\s*=\s*\d+', '', content)
    content = re.sub(r'ROW_FORMAT\s*=\s*\w+', '', content)
    content = re.sub(r'CHARACTER SET \w+ COLLATE \w+', '', content)

    # 5. tinyint → smallint
    lines = content.split('\n')
    new_lines = []
    for line in lines:
        # Only replace in DDL (CREATE TABLE), not in comments or INSERT
        if 'tinyint' in line.lower() and ('CREATE' in line or 'ALTER' in line or '  ' in line):
            line = re.sub(r'\btinyint\b', 'smallint', line, flags=re.IGNORECASE)
        new_lines.append(line)
    content = '\n'.join(new_lines)

    # 6. bit(1) → boolean
    content = re.sub(r'\bbit\(1\)\b', 'boolean', content)

    # 7. text → clob
    if 'CREATE TABLE' in content:
        content = re.sub(r'\btext\b', 'clob', content)

    # 8. Remove ON UPDATE CURRENT_TIMESTAMP
    content = re.sub(r'ON UPDATE CURRENT_TIMESTAMP(\(\d+\))?', '', content)

    # 9. datetime → timestamp
    # Only in CREATE TABLE context
    content = re.sub(r'\bdatetime\b', 'timestamp', content)

    # 10. Remove DEFAULT_GENERATED (MySQL 8 generated column default)
    content = re.sub(r'DEFAULT_GENERATED', '', content)

    # 11. bigint NOT NULL AUTO_INCREMENT → bigint AUTO_INCREMENT
    content = re.sub(r'bigint NOT NULL AUTO_INCREMENT', 'bigint AUTO_INCREMENT', content)

    # 12. Remove FOREIGN_KEY_CHECKS
    content = re.sub(r'SET FOREIGN_KEY_CHECKS\s*=\s*\d+;', '', content)

    # 13. Remove UNIQUE KEY / INDEX / KEY definitions that use dropped USING syntax
    # H2 supports UNIQUE and INDEX but with simpler syntax

    # 14. Remove COMMENT on columns and tables (H2 doesn't support)
    content = re.sub(r"COMMENT\s+'[^']*'", '', content)

    # 15. Clean up extra whitespace
    content = re.sub(r'\n\s*\n\s*\n+', '\n\n', content)

    # 16. Add DROP TABLE IF EXISTS (already there but ensure proper case)
    content = re.sub(r'DROP TABLE IF EXISTS (\w+)', r'DROP TABLE IF EXISTS \1', content)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("-- H2 Schema auto-generated from ruoyi-vue-pro.sql\n")
        f.write("-- Generated by convert_mysql_to_h2.py\n\n")
        f.write(content)

    print(f"Converted: {input_file} → {output_file}")

if __name__ == '__main__':
    input_file = sys.argv[1] if len(sys.argv) > 1 else 'mysql/ruoyi-vue-pro.sql'
    output_file = sys.argv[2] if len(sys.argv) > 2 else 'h2/h2-schema.sql'
    convert_mysql_to_h2(input_file, output_file)
